name: dart_flutter_macros_experimental
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-222.0.dev

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  json: ^0.20.2
  macros: 0.1.2-main.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

analyzer:
  enable-experiment:
    - macros